name: Format

permissions:
  contents: read

on:
  pull_request:
    paths:
      - ".npmrc"
      - "package.json"
      - "package-lock.json"
      - "**.yml"
      - "**.yaml"
      - "**.md"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: "25"

      - run: npm ci --ignore-scripts
      - run: ./node_modules/.bin/prettier --check "**/*.{yml,yaml}"
      - run: ./node_modules/.bin/prettier --check --prose-wrap always "**/*.md"
