on:
  push:
    branches: [main]
  pull_request:

name: Test

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          persist-credentials: false

      - name: Install
        run: |
          rustup toolchain install nightly --profile minimal --component miri,rustfmt,clippy --allow-downgrade
          rustup override set nightly

      - name: Format
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Test
        run: cargo test

      - name: Miri
        run: cargo miri test

      - name: Bench
        run: cargo bench
